spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://3307:localhost:3307/spring-boot-project-mysql-database
    username: root
    password: crissjazz98
  application:
    name: client-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        use_sql_comments: false
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
    fetchRegistry: true
server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8091
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
feign:
  hystrix:
    enabled: true
  ribbon:
    enabled: true
  circuitbreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
