server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
    fetchRegistry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: photo-service
              uri: lb://photo-service
              predicates:
                - Path=/photos/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/clients/**