management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/spring-boot-project-mysql-database
    username: ${USER_MYSQL_CONNECTION}
    password: ${PASSWORD_MYSQL_CONNECTION}
  data:
    mongodb:
      authentication-database: admin
      database: spring-boot-project-mongodb-photos-database
      username: ${USER_MONGODB_CONNECTION}
      password: ${PASSWORD_MONGODB_CONNECTION}
      port: '27017'
      host: localhost
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        use_sql_comments: 'false'
        format_sql: 'false'
        show_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
server:
  error:
    include-binding-errors: always
    include-message: always
  port: '8091'
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

