management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  data:
    mongodb:
      database: spring-boot-project-mongodb-photos-database
      username: root
      password: crissjazz98 # >:v
      port: '27017'
      host: localhost
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
server:
  error:
    include-binding-errors: always
    include-message: always
  port: '8091'

#eureka:
  #instance:
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #client:
    #serviceUrl:
      #defaultZone: http://localhost:8099/eureka/

